name: haniwa
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_native_splash: ^1.1.8+4
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4
  sign_button: ^2.0.0
  simple_logger: ^1.8.0+1
  cloud_firestore: ^2.2.0
  vibration: ^1.7.3
  flutter_local_notifications: ^6.0.0
  shared_preferences: ^2.0.6
  circular_countdown_timer: ^0.2.0
  lottie: ^1.0.1
  simple_animations: ^3.1.1
  confetti: ^0.5.5
  flutter_launcher_icons: ^0.9.0
  firebase_dynamic_links: ^2.0.6
  flutter_slidable: ^0.6.0
  firebase_storage: ^9.0.0
  http: ^0.13.3
  path_provider: ^2.0.2
  path: ^1.8.0
  nfc_manager: ^3.1.0
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  flutter_rating_bar: ^4.0.0
  percent_indicator: ^3.0.1
  cloud_functions: ^3.0.4
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/phone.svg
    - assets/images/haniwa.svg
    - assets/images/logo.png
    - assets/images/error_haniwa.png
    - assets/images/times_medal/3.png
    - assets/images/times_medal/5.png
    - assets/images/times_medal/10.png
    - assets/images/times_medal/15.png
    - assets/images/times_medal/30.png
    - assets/images/habit_medal/3.png
    - assets/images/habit_medal/5.png
    - assets/images/habit_medal/10.png
    - assets/images/habit_medal/15.png
    - assets/images/habit_medal/30.png
    - assets/lottiefiles/congratulations.json

flutter_native_splash:
  color: "#EC407A"
  color_dark: "#D81B60"
  image: assets/images/logo.png

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"
