name: haniwa
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_native_splash: ^1.1.8+4
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4
  sign_button: ^2.0.0
  simple_logger: ^1.8.0+1
  cloud_firestore: ^2.2.0
  vibration: ^1.7.3
  flutter_local_notifications: ^6.0.0
  shared_preferences: ^2.0.6
  circular_countdown_timer: ^0.2.0
  lottie: ^1.0.1
  simple_animations: ^3.1.1
  confetti: ^0.5.5
  firebase_dynamic_links: ^2.0.6
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/phone.svg
    - assets/images/haniwa.svg
    - assets/images/logo.svg
    - assets/lottiefiles/congratulations.json

flutter_native_splash:
  color: "#EC407A"
  color_dark: "#D81B60"
  image: assets/images/logo.png
